version: '3.9'

services:
  postgres_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: moulmahal
      POSTGRES_DB: moulmahal
      POSTGRES_USER: moulmahal

    networks:
      - database_network




volumes:
  postgres_data:

networks:
  database_network:
    driver: bridge