version: '3.9'

services:

  postgres_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: moulmahal
      POSTGRES_DB: moulmahal
      POSTGRES_USER: moulmahal
    volumes:
      - ./data/db:/var/lib/postgresql/data

  moulmahal:
    build: .
    command: bash -c "chmod +x ./run_server.sh && ./run_server.sh"
    volumes:
      - ./moulmahal:/app
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
