version: '3.9'

services:
  moulmahal:
    build: .
    ports:
      - "8000:8000"

  postgres_db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: moulmahal
      POSTGRES_DB: moulmahal
      POSTGRES_USER: moulmahal
