# Generated by Django 5.0.6 on 2024-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=30)),
                ('product_description', models.CharField(blank=True, max_length=300, null=True)),
                ('product_cost_price', models.FloatField(default=0)),
                ('product_sale_price', models.FloatField(default=0)),
                ('product_qrcode', models.CharField(max_length=128)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
