# Generated by Django 5.0.6 on 2024-05-19 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('client_address', models.CharField(default='Rue', max_length=100)),
                ('client_phone', models.CharField(default='00000000', max_length=100)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('cost_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost_type', models.CharField(max_length=30)),
                ('spending_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost_cmt', models.CharField(blank=True, max_length=500, null=True)),
                ('cost_recipe', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'costs',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_order', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.clients')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orders')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
