# Generated by Django 5.0.6 on 2024-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitems_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clients',
            constraint=models.UniqueConstraint(fields=('client_phone',), name='unique client phone'),
        ),
    ]
